;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	evil-backward-char
	evil-delete-char
	evil-forward-char
	sp-backward-delete-char
	sp-backward-kill-word
	sp-backward-sexp
	sp-backward-unwrap-sexp
	sp-delete-char
	sp-forward-slurp-sexp
	sp-kill-region
	sp-kill-word
	sp-unwrap-sexp
	))

(setq mc/cmds-to-run-once
      '(
	handle-switch-frame
	pixel-scroll-precision
	pixel-scroll-start-momentum
	text-scale-adjust
	))
