#! /bin/sh

/bin/bash -c /home/yaslam/.config/bspwm/autostart.sh
pgrep -x sxhkd > /dev/null || sxhkd -c /home/yaslam/.config/sxhkd/sxhkdrc &

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d I II III IV

bspc config border_width         2

gaps=12
bspc config window_gap          $gaps

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Xfce4-notifyd layer=above
bspc rule -a Xfce4-power-manager-settings state=floating
bspc rule -a Emacs state=tiled
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# External rules (for window title matching etc..)
bspc config external_rules_command /home/yaslam/.config/bspwm/rules.sh
