#!/bin/bash

### Tag all emails from "me" as "sent"
notmuch tag +sent -- from:YUZi54780@outlook.com

### Do some post-processing of emails here
# immediately archive all messages from "me"
notmuch tag -new -- tag:new and from:YUZi54780@outlook.com or tag:new and from:yaslam0x1@gmail.com

# archive all messages from "other"
notmuch tag -new -- tag:new and from:ashz.one@hotmail.com

# tag all messages to me as "personal"
notmuch tag +personal -- tag:new and to:YUZi54780@outlook.com

# tag all messages to other as "other"
notmuch tag +other -- tag:new and to:ashz.one@hotmail.com

# tag all messages urgent from "*noip*"
notmuch tag +urgent +noip -- tag:new and from:*noip* and subject:"Action Required"

# tag all messages urgent from "Important" emails
notmuch tag +urgent -- tag:new and subject:"Important" or tag:new and subject:"Action Required"

# tag all messages from RedHat mailing list
notmuch tag +redhat -- tag:new and from:errata@redhat.com

# tag all messages from Debian mailing list
notmuch tag +debian +personal -- tag:new and to:debian-security-announce@lists.debian.org

# tag all messages from Emacs-devel mailing list
# notmuch tag +emacs-devel +personal -- tag:new and to:emacs-devel@gnu.org

# tag all messages from bug-gnu-emacs mailing list
# notmuch tag +emacs-bugs +personal -- tag:new and to:debbugs.gnu.org

### After post-processing do stuff here
# finally, retag all "new" messages "inbox" and "unread"
notmuch tag +inbox +unread -new -- tag:new
