#!/bin/bash

### Do some post-processing of emails here
# immediately archive all messages from "me"
notmuch tag -new -- tag:new and from:YUZi54780@outlook.com or tag:new and from:yaslam0x1@gmail.com

# tag all messages urgent from "*noip*"
notmuch tag +urgent +noip -- tag:new and from:*noip* and subject:"Action Required"

# tag all messages urgent from "Important" emails
notmuch tag +urgent -- tag:new and subject:"Important" or tag:new and subject:"Action Required"

# tag all messages from RedHat mailing list
notmuch tag +redhat -- tag:new and from:errata@redhat.com

### After post-processing do stuff here
# finally, retag all "new" messages "inbox" and "unread"
notmuch tag +inbox +unread -new -- tag:new
